spring:
  application:
    name: springflix-posters

app:
  client:
    connectTimeout: 30s
    readTimeout: 30s
  tmdb:
    api:
      url: https://api.themoviedb.org
      key:
    images:
      url: https://image.tmdb.org/t/p/w500/

server:
  port: ${PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    metrics:
      export:
        enabled: false

---

spring:
  config:
    activate:
      on-cloud-platform: kubernetes

management:
  otlp:
    metrics:
      export:
        enabled: true
